[package]
name = "wobj"
version = "0.1.0"
edition = "2024"

[dependencies]
winnow = "0.7.14"
smallvec = "1.15.1"
ahash = "0.8.12"
indexmap = { version = "2.13.0", optional = true }

[features]
default = ["trimesh"]
trimesh = ["dep:indexmap"]
